### ISSUE TITLE
Ruby 3.1 checklist

### ISSUE THREAD

**Issue by palkan** [ruby-next/ruby-next#87]
The features from Ruby 3.1 currently missing in Ruby Next.

## Syntax

- [x] \* Command syntax in endless methods (`def foo() = puts "bar"`): https://bugs.ruby-lang.org/issues/17398

\* We only need to support this for Ruby 3.0. Older Rubies are automatically supported (since Parser recognizes this syntax and we transpile it).

## API

- [x] `Enumerable#compact`: https://bugs.ruby-lang.org/issues/17312
- [x] `Integer.try_convert`: https://bugs.ruby-lang.org/issues/15211, https://github.com/ruby/ruby/commit/301d194ee3b49e6b078eccb999dd538e9bfa8c7c
- [x] `MatchData#match`: https://bugs.ruby-lang.org/issues/18172, https://github.com/ruby/ruby/commit/09d724e6f846b4e53e8571d41ca7d3055d732d9f
- [ ] \*\*`Kernel#load` with a wrapping Module: https://bugs.ruby-lang.org/issues/6210, https://github.com/ruby/ruby/commit/b35b7a1ef25347735a6bb7c28ab7e77afea1d856

\*\* Not sure we want to support this one; but that could be an interesting challenge 🙂
